---
title: Dave Everitt
timezone: Asai/Phnom_Penh
collections:
  posts:
    title: Posts
    output: true
  milestones:
    title: Milestones
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: milestones
  values:
    title: 
    date: 2026-09-01 00:00:00 -0700
markdown: kramdown
highlighter: rouge
lsi: false
description: your resume
baseurl: ""
url: ""
color: "#f2f2f2"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README
  - Gemfile
